config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root "static#home"
  resources :languages, param: :slug, except: [:new, :create, :edit, :update, :delete] do
    resources :calls, only: [:new, :create, :show]
  end

  resources :users, param: :slug  

  scope '/admin' do
    get '/', to: "static#admin", as: "/admin"
    get '/login', to: "sessions#new"
    get '/signup', to: "users#new"
    post '/login', to: "sessions#create"
    resources :languages, param: :slug, only: [:new, :create, :edit, :update, :delete]
    resources :users, param: :slug
  end
  get 'auth/:provider/callback', to: 'sessions#omniauth'


  get "/signin", to: "users#new"
  get '/login', to: "sessions#new" 
  post '/login', to: 'sessions#create' 
  get "/logout", to: "sessions#delete"  
    

end

app/models/language.rb
class Language < ApplicationRecord
    has_many :calls 
    has_many :user_languages

    include Slug::InstanceMethods
    extend Slug::ClassMethods


    scope :search_by_language, -> (search) {where("name LIKE ?", "#{search}%")}
    
        # def self.search_by_language(search)
        #     if search 
        #         self.where("name LIKE ?", "#{search}%")
        #     else
        #         self.all
        #     end
        # end


end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates_presence_of :email, message: "Please fill out all fields"
    validates_uniqueness_of :email
    # validates :password, length: {minimum: 8, message: "Must have at least 8 characters"}
    validates :name, format: {without: /[0-9]/, message: "Name cannot contain numbers"}


    extend Slug::ClassMethods
    include UsersHelper

    has_many :user_languages
    has_many :languages, through: :user_languages


    #as a caller
    has_many :speaker_calls, foreign_key: "speaker_id", class_name: "Call"
    has_many :speakers, through: :speaker_calls, class_name: "User"

    #as a speaker
    has_many :caller_calls, foreign_key: "caller_id", class_name: "Call"
    has_many :callers, through: :caller_calls, class_name: "User"

    def self.can_speak(language)
        User.all.select {|u| u.languages.include?(language)}
    end
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
    before_action :set_language, only: [:edit, :update, :destroy]
    # before_action :is_admin?, only: [:new, :create, :edit, :update, :destroy]

    def index
        if params["search"]
            @languages = Language.search_by_language(params["search"])
        else
            @languages = Language.all
        end
    end

    def show
        @users = User.all
        @language = Language.find_by_slug(params[:slug])
        if current_user.languages.include?(@language)
            flash[:message] = "You cannot make a call in this language since you already speak it!"
            redirect_to languages_path
        end
        if @language.nil?  
            redirect_to languages_path
        end 
    end

    def new 
        if is_admin?
            @language = Language.new
        else
            redirect_to languages_path, message: "User not authorized"
        end
    end

    def create
        if is_admin?
            @language = Language.new(language_params)
            if @language.save
                redirect_to language_path
            else
                render 'new'
            end
        else
            redirect_to languages_path
        end
    end 


    private

    def set_language
        @language = Language.find_by(name: params[:name])
    end

    def language_params
        params.require(:language).permit(:name, :speaker, :caller)
    end

    def is_admin?
        current_user.admin == true
    end

end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/views/languages/_form.html.erb
<%= form_for @language do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.submit %>
<% end %>

app/views/languages/edit.html.erb
<%= render 'form' %>

app/views/languages/index.html.erb
<div class='center'><h1 class="center"> Practice Your Fluency! </h1>
    <p>Choose the language you want to practice with a native speaker:</p>

</div>
<div class='center'>
    <%= form_with(url:languages_path, method: :get) do |f| %>
        <%= f.label :search, "Search Language" %>
        <%= f.text_field :search %>
        <%= f.submit "Search" %>
    <% end %>    
</div> 

<ul class="center">



<% @languages.each do |language|%>
    <div><%= link_to language.name, language_path(language.slug) %></div>
<% end %>
</ul>    
    

app/views/languages/new.html.erb
<h1>new language, only admin </h1>
<%= render 'form' %>

app/views/languages/show.html.erb
<div class="center">
<h1 class="center"><%= @language.name %></h1>

<% u = [] %>
<% @users.each do |user| %>
    <% if user.language_ids.include?(@language.id) %>
        <% u << user %>
    <% end %>
<% end %>
    <% if u.count == 1 %>
        <p> There is 1 speaker for this language</p>
    <% else %>
        <p> There are <%= u.count %> speakers for this language</p>  
<% end %>

    </br>


        <h3>Call a native speaker!</h3>
        <%= link_to "Call", new_language_call_path(@language.slug), class:"button"%>
</div>