config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root "static#home"
  resources :languages, param: :slug, except: [:new, :create, :edit, :update, :delete] do
    resources :calls, only: [:new, :create, :show]
  end

  resources :users, param: :slug  

  scope '/admin' do
    get '/', to: "static#admin", as: "/admin"
    get '/login', to: "sessions#new"
    get '/signup', to: "users#new"
    post '/login', to: "sessions#create"
    resources :languages, param: :slug, only: [:new, :create, :edit, :update, :delete]
    resources :users, param: :slug
  end
  get 'auth/:provider/callback', to: 'sessions#omniauth'


  get "/signin", to: "users#new"
  get '/login', to: "sessions#new" 
  post '/login', to: 'sessions#create' 
  get "/logout", to: "sessions#delete"  
    

end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates_presence_of :email, message: "Please fill out all fields"
    validates_uniqueness_of :email
    # validates :password, length: {minimum: 8, message: "Must have at least 8 characters"}
    validates :name, format: {without: /[0-9]/, message: "Name cannot contain numbers"}


    extend Slug::ClassMethods
    include UsersHelper

    has_many :user_languages
    has_many :languages, through: :user_languages


    #as a caller
    has_many :speaker_calls, foreign_key: "speaker_id", class_name: "Call"
    has_many :speakers, through: :speaker_calls, class_name: "User"

    #as a speaker
    has_many :caller_calls, foreign_key: "caller_id", class_name: "Call"
    has_many :callers, through: :caller_calls, class_name: "User"

    def self.can_speak(language)
        User.all.select {|u| u.languages.include?(language)}
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :verified_user, only: [:new, :create]
    before_action :current_user
    before_action :set_user, only: [:show, :edit, :update]
    before_action :get_languages, only: [:show, :edit, :update, :new, :create]
    

    def new 
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.valid?
            @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user.slug) 
        else
            render 'new'
        end
    end
    
    

    def show
        if @user.nil?  
            redirect_to user_path(current_user.slug)
        elsif
            @user == !current_user
            redirect_to user_path(current_user.slug)
        end 
    end


    def edit
    end

    def update
        if @user.update(user_params)
            redirect_to user_path(@user.slug)
        else
            render :edit
        end
    end

    private

    def user_params
        params.require(:user).permit(
            :name,
            :username,
            :email,
            :password, 
            :password_confirmation,
            :language_ids => []
        )
    end

    def set_user 
        @user = User.find_by_slug(params[:slug])
    end 

    def get_languages
        @languages = Language.all
    end

    # def is_admin?
    #     if admin_url
    #         @user.admin = true
    #     end
    # end

end

app/helpers/users_helper.rb
module UsersHelper
    def slug
        self.username = self.email.split('@')[0].downcase.gsub(".", "")
    end

end

app/views/users/edit.html.erb
<div class="center">
<%= form_for @user, url: "/users/#{@user.slug}" do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
         <h4> 
            <%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:
        </h4>        
    
        <ul>
        <% @user.errors.full_messages.each do |message| %>
            <%= message %><br>
        <% end %>
        </ul>
        </div>
    <% end %>
    
    <div>
    <%= f.label :name, "Name" %><br>
    <%= f.text_field :name %>
    </div>

    <div>
    <%= f.label :username, "Username" %><br>
    <%= f.text_field :username %>
    </div>


    <div>
    <%= f.label :email, "Email" %><br>
    <%= f.email_field :email %>
    </div>

    <div>   

    <% f.label :language_ids, "What Languages do you speak?" %><br>
      <%= f.collection_check_boxes(:language_ids, @languages, :id, :name)%>
    </div>

    <div>
    <%= f.label :password, "Password" %><br>
    <%= f.password_field :password %>
    </div>

    <div>
    <%= f.label :password_confirmation, "Confirm Password" %><br>
    <%= f.password_field :password_confirmation %>
    </div>

    <br>

    <%= f.submit %>

<% end %>
</div>

app/views/users/new.html.erb
<div class="center">
<%= image_tag("FluentApp_Logo.png", width: '100px') %>
</div>

<div class='center'>
<h1 class="center"> Sign Up </h1>

<%= form_for @user do |f| %>

    <% if @user.errors.any? %>
    <div id="error_explanation">
     <h4> 
        <%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:
    </h4>        

    <ul>
    <% @user.errors.full_messages.each do |message| %>
        <%= message %>
        <% end %>
    </ul>
    </div>
<% end %>



<div>
<%= f.email_field :email, placeholder:"Email" %>
</div>

<br>
<div>
<%= f.password_field :password, placeholder:"Password" %>
</div>
<br>
<div>
<%= f.password_field :password_confirmation, placeholder:"Confirm Password" %>
</div>

<br>

<%= f.submit %>

<% end %>
</div>

app/views/users/show.html.erb
<div class="center">
<% if @user.name %>
    <h1 class="center"> Welcome, <%= @user.name %>!</h1>
<% else %>
    <h1 class="center"> Welcome! </h1>
<% end %>    

<% if @user.admin == true %>
    <h3>Admin User</h3>
<% end %>    


    <div>Username: <%= @user.username %></div>
    


<p>Languages you speak: </p>
<% if @user.languages.count == 0 %>
<br>
    <p> You have not set up your account! <br>
     Please go to settings and edit your account.</p>
<% else %>     
    <% @user.languages.each do |language| %>
        <%= link_to language.name, language_path(language.slug) %><br>
    <% end %>
<% end %>
</div>

<div>
<h4>Calls you've taken</h4>
    <ul>
        <% @user.speaker_calls.each do |call| %>
            <p><%= call.language.name %> | <%= call.schedule_time %> | <%= call.duration %></p>
        <% end %>
    </ul>   
</div>  
<br>
<div>
<h4>Calls you've done</h4>
    <ul>
        <% @user.caller_calls.each do |call| %>
            <p><%= call.language.name %> | <%= call.schedule_time %> | <%= call.duration %></p>
        <% end %>
    </ul>   
</div>  