config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root "static#home"
  resources :languages, param: :slug, except: [:new, :create, :edit, :update, :delete] do
    resources :calls, only: [:new, :create, :show]
  end

  resources :users, param: :slug  

  scope '/admin' do
    get '/', to: "static#admin", as: "/admin"
    get '/login', to: "sessions#new"
    get '/signup', to: "users#new"
    post '/login', to: "sessions#create"
    resources :languages, param: :slug, only: [:new, :create, :edit, :update, :delete]
    resources :users, param: :slug
  end
  get 'auth/:provider/callback', to: 'sessions#omniauth'


  get "/signin", to: "users#new"
  get '/login', to: "sessions#new" 
  post '/login', to: 'sessions#create' 
  get "/logout", to: "sessions#delete"  
    

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FluentApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Hind+Siliguri:wght@300&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    
    <% if current_user %>
      <div class="topnav">
          <%= link_to "Home", user_path(current_user.slug), class:'link'%>
          <%= link_to "Languages", languages_path, class:'link' %>
          <li class="dropdown">
            <a class="dropbtn" >Settings</a>
            <div class="dropdown-content">
                <%= link_to "Edit Account", edit_user_path(current_user.slug)%><br>
                <%= link_to "Log Out", logout_path %>
                </div>
                </li>    
                </div>
  
    <% end %>
    </head>

  <body>

  <%= flash[:message] %>
  

    <%= yield %>
  </body>
</html>